// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocationName() {
  return window['go']['main']['App']['GetLocationName']();
}

export function UpdateWeather() {
  return window['go']['main']['App']['UpdateWeather']();
}
