// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function GetLocationName():Promise<string>;

export function UpdateWeather():Promise<internal.CurrentWeather>;
