// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocationName() {
  return window['go']['main']['App']['GetLocationName']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function UpdateConfig() {
  return window['go']['main']['App']['UpdateConfig']();
}

export function UpdateWeather() {
  return window['go']['main']['App']['UpdateWeather']();
}
